# I want to avoid installing apps locally, so this is going to
# provide a simple docker wrapper for running the flex/bison commands.

FROM alpine:latest
RUN apk update && apk add flex bison

WORKDIR /workspace

